---
- name: Install git
  package:
    name:  git
    state: present

- name: Use ssh-agent on macOS
  blockinfile:
    block: |
      Host *
        UseKeychain yes
        AddKeysToAgent yes
    create: yes
    dest:   ~/.ssh/config

- name: Link git global ignore file
  file:
    dest:   "{{git_gitignore_global_path}}"
    force:  yes
    src:    "{{ansbile_git_client_gitignore_global_path}}"
    state:  link
  notify:
    - Configure the global ignore file

- name: Use global git ignore
  git_config:
    name:   core.excludesfile
    scope:  global
    value:  ~/.gitignore_global

- name: Set autostash
  git_config:
    name:   rebase.autoStash
    scope:  global
    value:  'true'

