---
- hosts: localhost
  roles:
    - role: git-client
      tags:
        - git
    - role: git-gpg
      tags:
        - git
        - git-gpg
        - gpg
    - role: homebrew-machine
      tags:
        - homebrew
    - role: rooland-provisioning.vim-machine
      tags:
        - editor
        - vim
    - role: ruby-dev
      tags:
        - dev
        - language
        - ruby
    - role: terminal
      tags:
        - terminal
    - role: zsh-terminal
      tags:
        - terminal
        - zsh
  vars:
    packages:
      - brew-pip
      - ffmpeg
      - gpp
      - htop-osx
      - icu4c
      - imagemagick
      - jpeg
      - libxml2
      - multimarkdown
      - node
      - openssl
      - potrace
      - sqlite
      - tree
      - wget
    apps:
      - package_name: caffeine
        app_name:     Caffeine
      - package_name: dash
        app_name:     Dash
      - package_name: firefox
        app_name:     Firefox
      - package_name: kaleidoscope
        app_name:     Kaleidoscope
      - package_name: marked
        app_name:     'Marked 2'
      - package_name: opera
        app_name:     Opera
      - package_name: reflector
        app_name:     Reflector
    rubymotion:
      platforms:
        - platform_name:  android
        - platform_name:  apple
    git_gpg:
      git:
        signing_key: CA391F82
