---
- hosts: localhost
  roles:
    - role: git-client
      tags:
        - git
    - role: git-gpg
      tags:
        - git
        - git-gpg
        - gpg
    - role: homebrew-machine
      tags:
        - homebrew
    - role: rooland-provisioning.vim-machine
      tags:
        - editor
        - vim
    - role: ruby-dev
      tags:
        - dev
        - language
        - ruby
    - role: terminal
      tags:
        - terminal
    - role: zsh-terminal
      tags:
        - terminal
        - zsh
    - role: neovim-machine
      tags:
        - neovim
    - kitty-terminal
  vars:
    git_gpg:
      git:
        signing_key: CA391F82
