---
- hosts: localhost
  roles:
    - git-client
    - role: git-gpg
      tags:
        - git
        - git-gpg
        - gpg
    - role: rooland-provisioning.atom-editor
      tags:
        - atom
        - editor
    - role: ruby-dev
      tags:
        - dev
        - language
        - ruby
    - terminal
    - vim-machine
    - zsh-terminal
  vars:
    atom_editor:
      packages:
        - package_name: atom-beautify
        - package_name: close-on-left
        - package_name: git-plus
        - package_name: markdown-scroll-sync
        - package_name: minimap
        - package_name: react
        - package_name: react-snippets
        - package_name: refactor
        - package_name: sort-lines
        - package_name: vim-mode-plus
    npm_packages:
      - bower
