---
- hosts: localhost
  roles:
    - git-client
    - homebrew-machine
    - mysql-machine
    - rooland-provisioning.atom-editor
    - ruby-dev
    - ssl-requester
    - terminal
    - vim-machine
    - zsh-terminal
  vars:
    packages:
      - brew-pip
      - ffmpeg
      - freetds
      - gmp # RVM - Ruby installation
      - htop-osx
      - icu4c
      - imagemagick
      - jpeg
      - libxml2
      - macvim
      - multimarkdown
      - nginx
      - nvm
      - postgresql
      - redis
      - sqlite
      - v8
      - wget
    apps:
      - package_name: caffeine
        app_name:     Caffeine
      - package_name: dash
        app_name:     Dash
      - package_name: firefox
        app_name:     Firefox
      - package_name: kaleidoscope
        app_name:     Kaleidoscope
      - package_name: limechat
        app_name:     LimeChat
      - package_name: marked
        app_name:     'Marked 2'
      - package_name: opera
        app_name:     Opera
      - package_name: pgadmin3
        app_name:     pgAdmin3
    npm_packages:
      - bower
    atom_editor:
      packages:
        - package_name: atom-beautify
        - package_name: git-plus
        - package_name: jira-issue-search
        - package_name: language-docker
        - package_name: markdown-scroll-sync
        - package_name: minimap
        - package_name: react
        - package_name: react-snippets
        - package_name: refactor
        - package_name: sort-lines
        - package_name: vim-mode
