---
- hosts: localhost
  roles:
    - git-client
    - role: git-gpg
      tags:
        - git
        - git-gpg
        - gpg
    - role: ruby-dev
      tags:
        - dev
        - language
        - ruby
    - terminal
    - role: rooland-provisioning.vim-machine
      tags:
        - editor
        - vim
    - zsh-terminal
  vars:
    git_gpg:
      git:
        signing_key: CA391F82
