---
- name:     Install ViM
  homebrew: name=vim state=present

- name:     Install ag for ag bundle
  homebrew: name=the_silver_searcher state=present

- name:     Install MacVim
  command:  brew cask install macvim creates="~/Applications/MacVim.app"

- name: Download Vundle
  git:  repo=https://github.com/gmarik/vundle.git
        dest=~/.vim/bundle/vundle

- name: Link configs
  file: '   src="{{ansbile_vim_machine_path}}/files/config"
            dest="~/.vim/config"
            state=link
            force=yes'

- name: Link vimrc
  file: '   src="{{ansbile_vim_machine_path}}/files/vimrc"
            dest="~/.vimrc"
            state=link
            force=yes'

- name: Create file for local only configs
  lineinfile: ' dest="~/.vim/localconfig.vim"
                state=present
                create=yes
                line="\" Intented for local only configurations"
              '

- name: Install Powerline font
  get_url:  url=https://github.com/Lokaltog/powerline-fonts/blob/master/InconsolataDz/Inconsolata-dz%20for%20Powerline.otf?raw=true
            dest=~/Library/Fonts

- name: Create dir for local history
  file: dest={{vim_local_history_path}}
        state=directory

- name:   Create repo for local history
  shell:  git init chdir={{vim_local_history_path}}
