---
- name:     Install ViM
  homebrew: name=vim state=present

- name:     Install MacVim
  command:  brew cask install macvim creates="~/Applications/MacVim.app"

- name: Download Vundle
  git:  repo=https://github.com/gmarik/vundle.git
        dest=~/.vim/bundle/vundle

- name: Link Vundlefile
  file: '   src="{{ansbile_vim_machine_path}}/files/Vundlefile"
            dest="~/.vim/Vundlefile"
            state=link
            force=yes'

- name: Link vimrc
  file: '   src="{{ansbile_vim_machine_path}}/files/vimrc"
            dest="~/.vimrc"
            state=link
            force=yes'

- name: Install Powerline font
  get_url:  url=https://github.com/Lokaltog/powerline-fonts/blob/master/InconsolataDz/Inconsolata-dz%20for%20Powerline.otf?raw=true
            dest=~/Library/Fonts
