set nocompatible              " be iMproved, required
filetype off                  " required

" Font for Powerline
set guifont=Inconsolata-dz\ for\ Powerline:h15
set shell=/bin/zsh

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
" alternatively, pass a path where Vundle should install bundles
"let path = '~/some/path/here'
"call vundle#rc(path)

" let Vundle manage Vundle, required
Bundle 'gmarik/vundle'

source ~/.vim/Vundlefile

filetype plugin indent on
colorscheme jellybeans

" NERDTree
nmap <leader>n :NERDTreeToggle<CR>
let NERDTreeHighlightCursorline=1
let NERDTreeIgnore = ['tmp', '.yardoc', 'pkg']
let g:NERDTreeWinPos = "right"
"No double scrollbar with NerdTree
set guioptions-=L

" Trailing spaces cleanup
autocmd BufWritePre * :%s/\s\+$//e

let g:solarized_termcolors=256

" Open new buffers
nmap <leader>s<left>   :leftabove  vnew<cr>
nmap <leader>s<right>  :rightbelow vnew<cr>
nmap <leader>s<up>     :leftabove  new<cr>
nmap <leader>s<down>   :rightbelow new<cr>

