---
- name: Install packages
  homebrew: name={{item}} state=present
  with_items: packages

- name: Install graphviz
  homebrew: name=graphviz state=present install_options=with-app

- include: ../../casked/tasks/main.yml

- name: Install Apps for OSX
  command: brew cask install {{item.package_name}} creates="~/Applications/{{item.app_name}}.app"
  with_items: apps
