---
- hosts: localhost
  tasks:
    - name: Install Homebrew
      command: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)" creates=/usr/local/bin/brew
    - name: Initialize cask
      command: brew tap phinze/cask creates=/usr/local/Library/Taps/phinze-cask
    - name: Install graphviz (with brew update)
      homebrew: name=graphviz state=present install_options=with-app update_homebrew=true
    - name: Install packages
      homebrew: name={{item}} state=present
      with_items:
        - icu4c
        - openssl
        - imagemagick
        - mongodb
        - jpeg
        - libxml2
        - redis
        - brew-pip
        - git
        - multimarkdown
        - mysql
        - sqlite
        - graphviz
        - libiconv
        - postgresql
        - elasticsearch
        - nginx
        - vim
        - htop-osx
        - node
        - wget
        - brew-cask
    - name: Install Apps for OSX
      command: brew cask install {{item.package_name}} creates="~/Applications/{{item.app_name}}.app"
      with_items:
        - package_name: google-chrome
          app_name:     'Google Chrome'
        - package_name: rubymine
          app_name:     RubyMine
        - package_name: textmate
          app_name:     TextMate
        - package_name: tower
          app_name:     Tower
        - package_name: kaleidoscope
          app_name:     Kaleidoscope
        - package_name: jewelrybox
          app_name:     JewelryBox
        - package_name: marked2
          app_name:     Marked
        - package_name: app-dot-net-orbit
          app_name:     Orbit
        - package_name: app-dot-net-wedge
          app_name:     Wedge
        - package_name: linkinus
          app_name:     Linkinus

    - name: Setup RubyGems
      lineinfile: "dest=~/.gemrc state=present create=yes line='gem: --no-ri --no-rdoc'"
    - name: Install Oh my zsh
      command: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh creates=~/.oh-my-zsh
    - name: TextMate as default editor
      lineinfile: dest=~/.zshrc state=present create=yes line='export EDITOR="/usr/local/bin/mate -w"'
    - name: Rack apps in development environmentt
      lineinfile: dest=~/.zshrc state=present create=yes line='export RACK_ENV=development'
    - name: Alias for dir "re-entering"
      lineinfile: dest=~/.zshrc state=present create=yes line='alias recd="cd ..;cd -"'
    - name: Oh my zsh plugins
      lineinfile: dest=~/.zshrc state=present create=yes line='plugins=(git rvm)'
      
