---
- name: Install Apps for OSX
  homebrew_cask: name={{item.package_name}} state=present
  with_items:
    - package_name: app-dot-net-orbit
      app_name:     Orbit
    - package_name: app-dot-net-wedge
      app_name:     Wedge
