---
- name: Install Oh my zsh
  command: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh creates=~/.oh-my-zsh

- name:       OMZ plugins
  lineinfile: dest=~/.zshrc
              state=present
              line='plugins=(git rvm terminalapp brew brew-cask vagrant ruby gitignore z)'
              regexp='^plugins'

- name:       OMZ theme
  lineinfile: dest=~/.zshrc state=present line='ZSH_THEME="aussiegeek"' regexp='^ZSH_THEME'

- name:       My zshrc contribution
  lineinfile: dest=~/.zshrc
              state=present
              regexp='^source .+zshrc$'
              line='source {{ansible_env['PWD']}}/roles/zsh-terminal/files/zshrc'

- name:   Link zshenv
  file:   src={{ansible_env['PWD']}}/roles/zsh-terminal/files/zshenv
          dest=~/.zshenv
          state=link

- name:   Link Ag ignore file
  file:   src={{ansible_env['PWD']}}/roles/zsh-terminal/files/agignore
          dest=~/.agignore
          state=link
