packages:
  - icu4c
  - openssl
  - imagemagick
  - mongodb
  - jpeg
  - libxml2
  - redis
  - brew-pip
  - git
  - multimarkdown
  - mysql
  - sqlite
  - graphviz
  - libiconv
  - postgresql
  - elasticsearch
  - nginx
  - vim
  - htop-osx
  - node
  - wget
  - brew-cask
apps:
  - package_name: google-chrome
    app_name:     'Google Chrome'
  - package_name: rubymine
    app_name:     RubyMine
  - package_name: textmate
    app_name:     TextMate
  - package_name: tower
    app_name:     Tower
  - package_name: kaleidoscope
    app_name:     Kaleidoscope
  - package_name: jewelrybox
    app_name:     JewelryBox
  - package_name: marked2
    app_name:     Marked
  - package_name: linkinus
    app_name:     Linkinus
